[package]
name = "proto_benchmarks"
version = "0.1.0"
authors = ["Chris MacNaughton <chris@centaurisolutions.nl>"]
build = "build.rs"

[dependencies]
protobuf = "*"
capnp = "*"

[build-dependencies]
capnpc = "*"
protobuf-codegen-pure = "~2"

[dev-dependencies]
criterion = "0.1.2"

# Reads

[[bench]]
name = "protobuf_basic_read_benchmark"
harness = false

[[bench]]
name = "capnp_basic_read_benchmark"
harness = false

[[bench]]
name = "protobuf_complex_read_benchmark"
harness = false

[[bench]]
name = "capnp_complex_read_benchmark"
harness = false

# Writes

[[bench]]
name = "protobuf_basic_write_benchmark"
harness = false

[[bench]]
name = "capnp_basic_write_benchmark"
harness = false

[[bench]]
name = "protobuf_complex_write_benchmark"
harness = false

[[bench]]
name = "capnp_complex_write_benchmark"
harness = false
